import LocalizedStrings from 'react-native-localization';

let strings = new LocalizedStrings({
  ar: {
    searchForUser: "ابحث عن مستخدم...",
    userNotFound: "المستخدم غير موجود!",
    firstName: "الاسم: ",
    femaleUsersScreenName: "المستخدمات",
    maleUsersScreenName: "المستخدمون",
    userDetails: "تفاصيل المستخدم",
    info: "معلومات",
    home: "الرئيسية",
    users: "المستخدمون",
    login: "تسجيل الدخول",
    signup: "التسجيل",
    enterEmail: "أدخل بريدك الإلكتروني",
    enterPassword: "أدخل كلمة المرور",
    emailRequired: "يجب إدخال الإيميل!",
    passwordRequired: "يجب إدخال كلمة المرور!",
    emailInvalid: "الإيميل المدخل غير صالح!",
    passwordShort: "ستة أحرف على الأقل",
    signupForUs: "سجل لدينا في التطبيق!",
    hasAccount: "لديك حساب مسبقاً!",
    settings: "الإعدادات",
    favoriteLanguage: "الرجاء، اختر لغتك المفضلة:",
    search: "البحث",
    forgetPasswordMessage: "نسيت كلمة المرور؟",
    confirm: "تأكيد",
    backToLogin: "العودة إلى تسجيل الدخول!",
    loggedIn: "تم تسجيل الدخول بنجاح!",
    logout: "تسجيل الخروج",
    email: "البريد الإلكتروني: ",
    endList: "نهاية القائمة!",
    chat: "محادثة",
    topics: "المواضيع",
    contactus: "التواصل",
    privacy: "الخصوصية"
  },
  en: {
    searchForUser: "Search for User...",
    userNotFound: "User not Found!",
    firstName: "Name: ",
    femaleUsersScreenName: "Female Users",
    maleUsersScreenName: "Male Users",
    userDetails: "User Details",
    info: "Information",
    home: "Home",
    users: "Users",
    login: "Login",
    signup: "Sign Up",
    enterEmail: "ُEnter your email",
    enterPassword: "Enter your password",
    emailRequired: "Email must be entered!",
    passwordRequired: "Password must be entered!",
    emailInvalid: "Inavalid email!",
    passwordShort: "At least 6 chatacters",
    signupForUs: "Sign up for us!",
    hasAccount: "Already have an account!",
    settings: "Settings",
    favoriteLanguage: "Please, Select your favorite language:",
    search: "Search",
    forgetPasswordMessage: "Forget your password?",
    confirm: "Confirm",
    backToLogin: "Back to Login!",
    loggedIn: "You are Logged In!",
    logout: "Log out",
    email: "Email Address: ",
    endList: "End of the List!",
    chat: "Chat",
    topics: "Topics",
    contactus: "Contanct Us",
    privacy: "Privacy"
  }
});

export default strings;